onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /fcgru_fsmd_tb/clk_tb
add wave -noupdate /fcgru_fsmd_tb/rst_tb
add wave -noupdate /fcgru_fsmd_tb/start_tb
add wave -noupdate /fcgru_fsmd_tb/ready_tb
add wave -noupdate /fcgru_fsmd_tb/uz_tb
add wave -noupdate /fcgru_fsmd_tb/ur_tb
add wave -noupdate /fcgru_fsmd_tb/uh_tb
add wave -noupdate /fcgru_fsmd_tb/wz_tb
add wave -noupdate /fcgru_fsmd_tb/wr_tb
add wave -noupdate /fcgru_fsmd_tb/wh_tb
add wave -noupdate /fcgru_fsmd_tb/bz_tb
add wave -noupdate /fcgru_fsmd_tb/br_tb
add wave -noupdate /fcgru_fsmd_tb/bh_tb
add wave -noupdate /fcgru_fsmd_tb/test
add wave -noupdate /fcgru_fsmd_tb/stop
add wave -noupdate /fcgru_fsmd_tb/timeout
add wave -noupdate /fcgru_fsmd_tb/samples_done
add wave -noupdate /fcgru_fsmd_tb/xn_duv
add wave -noupdate /fcgru_fsmd_tb/sn_1_duv
add wave -noupdate /fcgru_fsmd_tb/sn_duv
add wave -noupdate /fcgru_fsmd_tb/rn_duv
add wave -noupdate /fcgru_fsmd_tb/uz_duv
add wave -noupdate /fcgru_fsmd_tb/ur_duv
add wave -noupdate /fcgru_fsmd_tb/uh_duv
add wave -noupdate /fcgru_fsmd_tb/wz_duv
add wave -noupdate /fcgru_fsmd_tb/wr_duv
add wave -noupdate /fcgru_fsmd_tb/wh_duv
add wave -noupdate /fcgru_fsmd_tb/bz_duv
add wave -noupdate /fcgru_fsmd_tb/br_duv
add wave -noupdate /fcgru_fsmd_tb/bh_duv
add wave -noupdate /fcgru_fsmd_tb/finished_sample_duv
add wave -noupdate /fcgru_fsmd_tb/DUV/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/start
add wave -noupdate /fcgru_fsmd_tb/DUV/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/xn
add wave -noupdate /fcgru_fsmd_tb/DUV/sn
add wave -noupdate /fcgru_fsmd_tb/DUV/uz
add wave -noupdate /fcgru_fsmd_tb/DUV/ur
add wave -noupdate /fcgru_fsmd_tb/DUV/uh
add wave -noupdate /fcgru_fsmd_tb/DUV/wz
add wave -noupdate /fcgru_fsmd_tb/DUV/wr
add wave -noupdate /fcgru_fsmd_tb/DUV/wh
add wave -noupdate /fcgru_fsmd_tb/DUV/bz
add wave -noupdate /fcgru_fsmd_tb/DUV/br
add wave -noupdate /fcgru_fsmd_tb/DUV/bh
add wave -noupdate /fcgru_fsmd_tb/DUV/finished_sample
add wave -noupdate /fcgru_fsmd_tb/DUV/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/xn_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/xn_next
add wave -noupdate /fcgru_fsmd_tb/DUV/wr_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/wz_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/wh_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/ur_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/uz_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/uh_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/br_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/bz_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/bh_tab
add wave -noupdate /fcgru_fsmd_tb/DUV/sample_cnt_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/sample_cnt_next
add wave -noupdate /fcgru_fsmd_tb/DUV/dec_sample_cnt
add wave -noupdate /fcgru_fsmd_tb/DUV/sample_cnt_is_zero
add wave -noupdate /fcgru_fsmd_tb/DUV/start_units
add wave -noupdate /fcgru_fsmd_tb/DUV/units_ready
add wave -noupdate /fcgru_fsmd_tb/DUV/rn
add wave -noupdate /fcgru_fsmd_tb/DUV/sn_1_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/sn_1_next
add wave -noupdate /fcgru_fsmd_tb/DUV/sn_1_temp
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/xn
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/sn_1
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/rn
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/uz
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ur
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/uh
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/wz
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/wr
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/wh
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/bz
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/br
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/bh
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/snj
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/rnj
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/rnj_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/rnj_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/rnj_rec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/rnj_dir_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/znj_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/znj_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/znj_rec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/znj_dir_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/hnj_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/hnj_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/hnj_rec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/hnj_dir_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/elemwise_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/snj_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/snj_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start_elemwise
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready_elemwise
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start_z_rec
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start_r_rec
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start_h_rec
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start_z_dir
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start_r_dir
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/start_h_dir
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready_z_rec
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready_r_rec
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready_h_rec
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready_z_dir
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready_r_dir
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ready_h_dir
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/a_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/b_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/z_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/a_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/a_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/b_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/b_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/k_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/k_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/acc_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/acc_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/k_count0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/a_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/b_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/add_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_DIR/dec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/a_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/b_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/z_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/a_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/a_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/b_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/b_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/k_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/k_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/acc_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/acc_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/k_count0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/a_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/b_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/add_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ZN_REC/dec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/a_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/b_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/z_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/a_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/a_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/b_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/b_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/k_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/k_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/acc_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/acc_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/k_count0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/a_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/b_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/add_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_DIR/dec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/a_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/b_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/z_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/a_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/a_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/b_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/b_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/k_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/k_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/acc_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/acc_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/k_count0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/a_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/b_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/add_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/RN_REC/dec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/a_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/b_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/z_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/a_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/a_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/b_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/b_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/k_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/k_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/acc_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/acc_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/k_count0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/a_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/b_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/add_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_DIR/dec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/a_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/b_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/z_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/a_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/a_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/b_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/b_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/k_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/k_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/acc_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/acc_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/k_count0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/a_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/b_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/add_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/HN_REC/dec_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/start
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/clk
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/rst
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/a_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/b_in
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/ready
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/z_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/state_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/state_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/a_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/a_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/b_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/b_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/k_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/k_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/mult_reg
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/mult_next
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/k_count0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/a_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/b_in0
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/mult_out
add wave -noupdate /fcgru_fsmd_tb/DUV/GEN_LAYER(0)/GRU_UNIT/ELEMWISE_PROD/dec_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 125
configure wave -valuecolwidth 160
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {27114 ps}
