onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /gru_fsmd_tb/clk_tb
add wave -noupdate /gru_fsmd_tb/rst_tb
add wave -noupdate /gru_fsmd_tb/start_tb
add wave -noupdate /gru_fsmd_tb/ready_tb
add wave -noupdate /gru_fsmd_tb/xn_tb
add wave -noupdate /gru_fsmd_tb/uz_tb
add wave -noupdate /gru_fsmd_tb/ur_tb
add wave -noupdate /gru_fsmd_tb/uh_tb
add wave -noupdate /gru_fsmd_tb/wz_tb
add wave -noupdate /gru_fsmd_tb/wr_tb
add wave -noupdate /gru_fsmd_tb/wh_tb
add wave -noupdate /gru_fsmd_tb/bz_tb
add wave -noupdate /gru_fsmd_tb/br_tb
add wave -noupdate /gru_fsmd_tb/bh_tb
add wave -noupdate /gru_fsmd_tb/test
add wave -noupdate /gru_fsmd_tb/stop
add wave -noupdate /gru_fsmd_tb/xn_duv
add wave -noupdate /gru_fsmd_tb/sn_1_duv
add wave -noupdate /gru_fsmd_tb/rn_duv
add wave -noupdate /gru_fsmd_tb/uz_duv
add wave -noupdate /gru_fsmd_tb/ur_duv
add wave -noupdate /gru_fsmd_tb/uh_duv
add wave -noupdate /gru_fsmd_tb/wz_duv
add wave -noupdate /gru_fsmd_tb/wr_duv
add wave -noupdate /gru_fsmd_tb/wh_duv
add wave -noupdate /gru_fsmd_tb/bz_duv
add wave -noupdate /gru_fsmd_tb/br_duv
add wave -noupdate /gru_fsmd_tb/bh_duv
add wave -noupdate /gru_fsmd_tb/snj_duv
add wave -noupdate /gru_fsmd_tb/rnj_duv
add wave -noupdate /gru_fsmd_tb/DUV/clk
add wave -noupdate /gru_fsmd_tb/DUV/rst
add wave -noupdate /gru_fsmd_tb/DUV/start
add wave -noupdate /gru_fsmd_tb/DUV/ready
add wave -noupdate /gru_fsmd_tb/DUV/xn
add wave -noupdate /gru_fsmd_tb/DUV/sn_1
add wave -noupdate /gru_fsmd_tb/DUV/rn
add wave -noupdate /gru_fsmd_tb/DUV/uz
add wave -noupdate /gru_fsmd_tb/DUV/ur
add wave -noupdate /gru_fsmd_tb/DUV/uh
add wave -noupdate /gru_fsmd_tb/DUV/wz
add wave -noupdate /gru_fsmd_tb/DUV/wr
add wave -noupdate /gru_fsmd_tb/DUV/wh
add wave -noupdate /gru_fsmd_tb/DUV/bz
add wave -noupdate /gru_fsmd_tb/DUV/br
add wave -noupdate /gru_fsmd_tb/DUV/bh
add wave -noupdate /gru_fsmd_tb/DUV/snj
add wave -noupdate /gru_fsmd_tb/DUV/rnj
add wave -noupdate /gru_fsmd_tb/DUV/rnj_reg
add wave -noupdate /gru_fsmd_tb/DUV/rnj_next
add wave -noupdate /gru_fsmd_tb/DUV/rnj_rec_out
add wave -noupdate /gru_fsmd_tb/DUV/rnj_dir_out
add wave -noupdate /gru_fsmd_tb/DUV/znj_reg
add wave -noupdate /gru_fsmd_tb/DUV/znj_next
add wave -noupdate /gru_fsmd_tb/DUV/znj_rec_out
add wave -noupdate /gru_fsmd_tb/DUV/znj_dir_out
add wave -noupdate /gru_fsmd_tb/DUV/hnj_reg
add wave -noupdate /gru_fsmd_tb/DUV/hnj_next
add wave -noupdate /gru_fsmd_tb/DUV/hnj_rec_out
add wave -noupdate /gru_fsmd_tb/DUV/hnj_dir_out
add wave -noupdate /gru_fsmd_tb/DUV/elemwise_reg
add wave -noupdate /gru_fsmd_tb/DUV/elemwise_next
add wave -noupdate /gru_fsmd_tb/DUV/elemwise_out
add wave -noupdate /gru_fsmd_tb/DUV/snj_reg
add wave -noupdate /gru_fsmd_tb/DUV/snj_next
add wave -noupdate /gru_fsmd_tb/DUV/start_elemwise
add wave -noupdate /gru_fsmd_tb/DUV/ready_elemwise
add wave -noupdate /gru_fsmd_tb/DUV/start_z_rec
add wave -noupdate /gru_fsmd_tb/DUV/start_r_rec
add wave -noupdate /gru_fsmd_tb/DUV/start_h_rec
add wave -noupdate /gru_fsmd_tb/DUV/start_z_dir
add wave -noupdate /gru_fsmd_tb/DUV/start_r_dir
add wave -noupdate /gru_fsmd_tb/DUV/start_h_dir
add wave -noupdate /gru_fsmd_tb/DUV/ready_z_rec
add wave -noupdate /gru_fsmd_tb/DUV/ready_r_rec
add wave -noupdate /gru_fsmd_tb/DUV/ready_h_rec
add wave -noupdate /gru_fsmd_tb/DUV/ready_z_dir
add wave -noupdate /gru_fsmd_tb/DUV/ready_r_dir
add wave -noupdate /gru_fsmd_tb/DUV/ready_h_dir
add wave -noupdate /gru_fsmd_tb/DUV/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/state_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/start
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/clk
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/rst
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/a_in
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/b_in
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/ready
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/z_out
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/state_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/a_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/a_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/b_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/b_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/k_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/k_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/acc_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/acc_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/k_count0
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/a_in0
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/b_in0
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/add_out
add wave -noupdate /gru_fsmd_tb/DUV/ZN_DIR/dec_out
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/start
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/clk
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/rst
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/a_in
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/b_in
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/ready
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/z_out
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/state_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/a_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/a_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/b_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/b_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/k_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/k_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/acc_reg
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/acc_next
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/k_count0
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/a_in0
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/b_in0
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/add_out
add wave -noupdate /gru_fsmd_tb/DUV/ZN_REC/dec_out
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/start
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/clk
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/rst
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/a_in
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/b_in
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/ready
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/z_out
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/state_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/a_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/a_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/b_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/b_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/k_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/k_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/acc_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/acc_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/k_count0
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/a_in0
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/b_in0
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/add_out
add wave -noupdate /gru_fsmd_tb/DUV/RN_DIR/dec_out
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/start
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/clk
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/rst
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/a_in
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/b_in
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/ready
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/z_out
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/state_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/a_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/a_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/b_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/b_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/k_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/k_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/acc_reg
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/acc_next
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/k_count0
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/a_in0
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/b_in0
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/add_out
add wave -noupdate /gru_fsmd_tb/DUV/RN_REC/dec_out
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/start
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/clk
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/rst
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/a_in
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/b_in
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/ready
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/z_out
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/state_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/a_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/a_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/b_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/b_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/k_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/k_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/acc_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/acc_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/k_count0
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/a_in0
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/b_in0
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/add_out
add wave -noupdate /gru_fsmd_tb/DUV/HN_DIR/dec_out
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/start
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/clk
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/rst
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/a_in
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/b_in
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/ready
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/z_out
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/state_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/a_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/a_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/b_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/b_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/k_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/k_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/acc_reg
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/acc_next
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/k_count0
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/a_in0
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/b_in0
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/add_out
add wave -noupdate /gru_fsmd_tb/DUV/HN_REC/dec_out
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/start
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/clk
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/rst
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/a_in
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/b_in
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/ready
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/z_out
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/state_reg
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/state_next
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/a_reg
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/a_next
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/b_reg
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/b_next
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/k_reg
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/k_next
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/mult_reg
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/mult_next
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/k_count0
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/a_in0
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/b_in0
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/mult_out
add wave -noupdate /gru_fsmd_tb/DUV/ELEMWISE_PROD/dec_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors
quietly wave cursor active 0
configure wave -namecolwidth 261
configure wave -valuecolwidth 140
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {32045 ns}
